baseURL = 'https://blog.3css.com/'
languageCode = 'zh-CN'
title = 'X2的主页'
theme = 'hugo-book'
hasCJKLanguage = true

[markup]
    [markup.highlight]
        style = 'paraiso-light'     # style demos https://pygments.org/demo/
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true    # 允许渲染原始 HTML

[params]
    BookRepo = 'https://github.com/cmdfas/x2-blog'
    BookLogo = 'x2-logo.png'
    BookMenuBundle = '/menu'
    BookServiceWorker = true  # 启用 SW，重复访问直接走缓存
    
    [params.cdnPrefixes]
        default = "https://static.cmdfas.top"
        cn = "https://static.3css.com"
        en = "https://static.cmdfas.top"


